# Generated by Django 5.2.5 on 2025-11-04 03:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'indexes': [
                    models.Index(fields=['nombre'], name='products_ca_nombre_0f0d20_idx')
                ],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(
                    max_length=50,
                    unique=True,
                    validators=[
                        django.core.validators.RegexValidator(
                            '^[A-Z0-9\\-_.]{3,50}$',
                            'SKU inválido (usa A-Z, 0-9, -, _, .)'
                        )
                    ],
                    verbose_name='SKU'
                )),
                ('ean_upc', models.CharField(
                    blank=True,
                    max_length=14,
                    null=True,
                    unique=True,
                    validators=[
                        django.core.validators.RegexValidator(
                            '^\\d{8}(\\d{4,6})?$',
                            'EAN/UPC debe ser 8/12/13/14 dígitos'
                        )
                    ],
                    verbose_name='EAN/UPC'
                )),
                ('nombre', models.CharField(max_length=191, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('uom_compra', models.CharField(
                    choices=[('UN', 'Unidad'), ('CAJA', 'Caja'), ('KG', 'Kilogramos')],
                    default='UN',
                    max_length=10,
                    verbose_name='UoM de compra'
                )),
                ('uom_venta', models.CharField(
                    choices=[('UN', 'Unidad'), ('CAJA', 'Caja'), ('KG', 'Kilogramos')],
                    default='UN',
                    max_length=10,
                    verbose_name='UoM de venta'
                )),
                ('factor_conversion', models.DecimalField(
                    decimal_places=4,
                    default=1,
                    max_digits=10,
                    validators=[django.core.validators.MinValueValidator(0.0001)],
                    verbose_name='Factor conversión'
                )),
                ('costo_estandar', models.DecimalField(
                    blank=True,
                    decimal_places=4,
                    max_digits=12,
                    null=True,
                    validators=[django.core.validators.MinValueValidator(0)],
                    verbose_name='Costo estándar'
                )),
                ('precio_venta', models.DecimalField(
                    blank=True,
                    decimal_places=2,
                    max_digits=12,
                    null=True,
                    validators=[django.core.validators.MinValueValidator(0)],
                    verbose_name='Precio de venta'
                )),
                ('impuesto_iva', models.DecimalField(
                    decimal_places=2,
                    default=19,
                    max_digits=5,
                    validators=[
                        django.core.validators.MinValueValidator(0),
                        django.core.validators.MaxValueValidator(25)
                    ],
                    verbose_name='IVA (%)'
                )),
                ('stock_minimo', models.DecimalField(
                    decimal_places=3,
                    default=0,
                    max_digits=12,
                    validators=[django.core.validators.MinValueValidator(0)],
                    verbose_name='Stock mínimo'
                )),
                ('stock_maximo', models.DecimalField(
                    blank=True,
                    decimal_places=3,
                    max_digits=12,
                    null=True,
                    validators=[django.core.validators.MinValueValidator(0)],
                    verbose_name='Stock máximo'
                )),
                ('punto_reorden', models.DecimalField(
                    blank=True,
                    decimal_places=3,
                    max_digits=12,
                    null=True,
                    validators=[django.core.validators.MinValueValidator(0)],
                    verbose_name='Punto de reorden'
                )),
                ('perecible', models.BooleanField(default=False, verbose_name='Perecible')),
                ('control_por_lote', models.BooleanField(default=False, verbose_name='Control por lote')),
                ('control_por_serie', models.BooleanField(default=False, verbose_name='Control por serie')),
                ('url_imagen', models.URLField(blank=True, verbose_name='URL Imagen')),
                ('url_ficha_tecnica', models.URLField(blank=True, verbose_name='URL Ficha técnica')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('categoria', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='productos',
                    to='products.categoria',
                    verbose_name='Categoría'
                )),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [
                    models.Index(fields=['sku'], name='products_pr_sku_959014_idx'),
                    models.Index(fields=['nombre'], name='products_pr_nombre_203300_idx'),
                    models.Index(fields=['categoria'], name='products_pr_categor_729bab_idx'),
                    models.Index(fields=['activo'], name='products_pr_activo_5016eb_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(
                        check=(
                            models.Q(precio_venta__isnull=True) |
                            models.Q(precio_venta__gte=models.F('costo_estandar'))
                        ),
                        name='prod_precio_mayor_igual_costo'
                    ),
                    models.CheckConstraint(
                        check=models.Q(
                            impuesto_iva__gte=0,
                            impuesto_iva__lte=25
                        ),
                        name='prod_iva_0_25'
                    ),
                    models.CheckConstraint(
                        check=(
                            models.Q(stock_maximo__isnull=True) |
                            models.Q(stock_maximo__gte=models.F('stock_minimo'))
                        ),
                        name='prod_stockmax_ge_min'
                    ),
                    models.CheckConstraint(
                        check=(
                            models.Q(punto_reorden__isnull=True) |
                            models.Q(punto_reorden__gte=models.F('stock_minimo'))
                        ),
                        name='prod_reorden_ge_min'
                    ),
                ],
            },
        ),
    ]
