# Generated by Django 5.2.5 on 2025-11-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='uom_compra',
            field=models.CharField(choices=[('UN', 'Unidad'), ('CAJA', 'Caja'), ('KG', 'Kilogramos'), ('GR', 'Gramos'), ('PQ', 'Paquete'), ('DISP', 'Display'), ('BOL', 'Bolsa')], default='UN', max_length=10, verbose_name='UoM de compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='uom_venta',
            field=models.CharField(choices=[('UN', 'Unidad'), ('CAJA', 'Caja'), ('KG', 'Kilogramos'), ('GR', 'Gramos'), ('PQ', 'Paquete'), ('DISP', 'Display'), ('BOL', 'Bolsa')], default='UN', max_length=10, verbose_name='UoM de venta'),
        ),
    ]
