# Generated by Django 5.2.5 on 2025-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_producto_uom_compra_alter_producto_uom_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url_imagen',
            field=models.URLField(blank=True, null=True, verbose_name='URL Imagen'),
        ),
    ]
