# Generated by Django 5.2.5 on 2025-11-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_producto_url_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url_ficha_tecnica',
            field=models.URLField(blank=True, null=True, verbose_name='URL Ficha técnica'),
        ),
    ]
