# Generated by Django 5.2.5 on 2025-11-04 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('transactional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='creado_por',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Creado por'
            ),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='movimientos',
                to='products.producto',
                verbose_name='Producto'
            ),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='suppliers.proveedor',
                verbose_name='Proveedor'
            ),
        ),
        migrations.AddField(
            model_name='stock',
            name='bodega',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stocks',
                to='transactional.bodega',
                verbose_name='Bodega'
            ),
        ),
        migrations.AddField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stocks',
                to='products.producto',
                verbose_name='Producto'
            ),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo', 'fecha'], name='transaction_tipo_6e9cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto'], name='transaction_product_66825e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['bodega_origen'], name='transaction_bodega__b83f02_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['bodega_destino'], name='transaction_bodega__c5f569_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['lote'], name='transaction_lote_a0f54e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['serie'], name='transaction_serie_ca4b12_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['producto', 'bodega'], name='transaction_product_a2afbf_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['lote'], name='transaction_lote_8e0c65_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['serie'], name='transaction_serie_08ed26_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['fecha_vencimiento'], name='transaction_fecha_v_89ce1f_idx'),
        ),

        # 🔥 CORRECCIÓN IMPORTANTE AQUÍ
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(
                check=models.Q(cantidad__gte=0),
                name='stock_cantidad_ge_0'
            ),
        ),

        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('producto', 'bodega', 'lote', 'serie', 'fecha_vencimiento')},
        ),
    ]
