# Generated by Django 5.2.5 on 2025-12-10 21:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_producto_url_ficha_tecnica'),
        ('suppliers', '0001_initial'),
        ('transactional', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='stock_cantidad_ge_0',
        ),
        migrations.RemoveIndex(
            model_name='bodega',
            name='transaction_nombre_deebb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='transaction_tipo_6e9cb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='transaction_product_66825e_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='transaction_bodega__b83f02_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='transaction_bodega__c5f569_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='transaction_lote_a0f54e_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='transaction_serie_ca4b12_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='transaction_product_a2afbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='transaction_lote_8e0c65_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='transaction_serie_08ed26_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='transaction_fecha_v_89ce1f_idx',
        ),
        migrations.AlterField(
            model_name='bodega',
            name='capacidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mov_destino', to='transactional.bodega'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='bodega_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mov_origen', to='transactional.bodega'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.proveedor'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución'), ('TRANSFERENCIA', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='transactional.bodega'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.producto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
