# Generated by Django 5.2.5 on 2025-11-04 03:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9Kk\\.\\-]{7,20}$', 'RUT/NIF inválido')], verbose_name='RUT/NIF')),
                ('razon_social', models.CharField(max_length=191, verbose_name='Razón social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=191, verbose_name='Nombre de fantasía')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]{6,30}$', 'Teléfono inválido')], verbose_name='Teléfono')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=128, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Chile', max_length=64, verbose_name='País')),
                ('condiciones_pago', models.CharField(max_length=120, verbose_name='Condiciones de pago')),
                ('moneda', models.CharField(default='CLP', max_length=8, verbose_name='Moneda')),
                ('contacto_principal_nombre', models.CharField(blank=True, max_length=120, verbose_name='Contacto principal (nombre)')),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254, verbose_name='Contacto principal (email)')),
                ('contacto_principal_telefono', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]{6,30}$', 'Teléfono inválido')], verbose_name='Contacto principal (teléfono)')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['rut_nif'], name='suppliers_p_rut_nif_e39678_idx'), models.Index(fields=['razon_social'], name='suppliers_p_razon_s_193a02_idx'), models.Index(fields=['estado'], name='suppliers_p_estado_c9b100_idx'), models.Index(fields=['activo'], name='suppliers_p_activo_5cbbba_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
                ('lead_time_dias', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Lead time (días)')),
                ('minimo_lote', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Mínimo por lote')),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)')),
                ('preferente', models.BooleanField(default=False, verbose_name='Proveedor preferente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='products.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='suppliers.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor por Producto',
                'verbose_name_plural': 'Proveedores por Producto',
                'indexes': [models.Index(fields=['producto'], name='suppliers_p_product_bdd889_idx'), models.Index(fields=['proveedor'], name='suppliers_p_proveed_1986c1_idx'), models.Index(fields=['preferente'], name='suppliers_p_prefere_579a43_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('preferente', True)), fields=('producto',), name='unico_proveedor_preferente_por_producto')],
                'unique_together': {('proveedor', 'producto')},
            },
        ),
    ]
