# Generated by Django 5.2.5 on 2025-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_options_usuario_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Código de verificación para primer acceso', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forzar cambio de contraseña al iniciar'),
        ),
    ]
