# Generated by Django 5.2.5 on 2025-11-16 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_invite_code_usuario_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Formato inválido: debe ser +569XXXXXXXX (12 caracteres).', regex='^\\+569\\d{8}$')], verbose_name='Teléfono'),
        ),
    ]
