# Generated by Django 5.2.5 on 2025-11-18 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos_login',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Formato inválido: usa +569XXXXXXXX o 9XXXXXXXXX (9 dígitos).', regex='^(\\+569\\d{8}|9\\d{8})$')], verbose_name='Teléfono'),
        ),
    ]
