"""
Django settings for lilis_erp project.
 
Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os, sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Añadimos la carpeta 'apps' al sys.path para que Django pueda encontrar las aplicaciones.
# Esto permite usar 'apps.products', 'apps.account', etc. en todo el proyecto.
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(&au%ml(#0nw-ulsjog4gr8y6vm=5-t+79^esejf+o@v2ir&47'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Asegúrate de que esto esté en False para producción


ALLOWED_HOSTS = [
    '52.1.66.83',   # producción (EC2)
    '127.0.0.1',    # desarrollo local
    'localhost',    # desarrollo local
]

CSRF_TRUSTED_ORIGINS = [
    'http://52.1.66.83',
    'https://52.1.66.83',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]


# Configuración de login y logout
LOGIN_REDIRECT_URL = 'main'       # Redirige aquí después de iniciar sesión
LOGOUT_REDIRECT_URL = 'login'     # Redirige aquí después de cerrar sesión
LOGIN_URL = 'login'               # Página de login por defecto (sin namespace)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps internas
    'apps.account',
    'apps.users',
    'apps.products',
    'apps.suppliers',
    'apps.transactional',
    'apps.api',

    # DRF
    'rest_framework',
    'rest_framework_simplejwt',

    # Swagger
    'drf_yasg',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Middleware corregido (evita bloquear API/Swagger)
    'apps.account.middleware.ForcePasswordChangeMiddleware',
]

ROOT_URLCONF = 'lilis_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Aquí le decimos a Django que busque plantillas en la carpeta 'templates'
        # en la raíz del proyecto (BASE_DIR).
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lilis_erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lilis_erp',   # Nombre de tu base de datos
        'USER': 'admin-erp',            # Usuario por defecto de WAMP
        'PASSWORD': 'Ventana#123',            # Vacío si no configuraste contraseña
        'HOST': 'localhost',       # Conexión local
        'PORT': '3306',            # Puerto por defecto de MySQL
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # ============
    # FORMATTERS
    # ============
    'formatters': {
        'audit_formatter': {
            'format': '{asctime} | {levelname} | {message}',
            'style': '{',
        },
    },

    # ============
    # HANDLERS
    # ============
    'handlers': {

        # --- Handler que ya tenías ---
        'login_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'login.log',
        },

        # --- Nuevo handler para auditoría ---
        'audit_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR /'audit.log',
            'formatter': 'audit_formatter',
        },
    },

    # ============
    # LOGGERS
    # ============
    'loggers': {

        # --- Logger que ya existía ---
        'login_secure': {
            'handlers': ['login_file'],
            'level': 'INFO',
            'propagate': False,
        },

        # --- NUEVO logger audit ---
        'auditoria': {
            'handlers': ['audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


AUTH_USER_MODEL = 'users.Usuario'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Le decimos a Django que busque archivos estáticos en la carpeta 'static'
# que está en la raíz del proyecto (BASE_DIR).
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

HANDLER403 = "lilis_erp.views.handler403"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "erpdulceria@gmail.com"          
EMAIL_HOST_PASSWORD = "kkprkdpvjskveuve"        
DEFAULT_FROM_EMAIL = "Dulcería Lilis ERP <erpdulceria@gmail.com>"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# --- Dominio fijo para los enlaces de recuperación de contraseña ---
PASSWORD_RESET_DOMAIN = "52.1.66.83"   # IP pública de tu instancia EC2 "3.85.33.49"
PASSWORD_RESET_PROTOCOL = "http"       # usa "https" si tienes SSL en la instancia

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


